# src/main/resources/application.yml
spring:
  application:
    name: prismaBack
  datasource:
    url: jdbc:mysql://localhost:3306/db_prisma
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${MY_APP_OAUTH_CLIENT_ID}
            client-secret: ${MY_APP_OAUTH_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
        provider:
          google:
            user-name-attribute: email

# Configuración JWT
jwt:
  secret: ${MY_APP_JWT_ENCRYPTION_KEY}
  expiration: 3600000

server:
  port: 8080

# Configuración de CORS para permitir peticiones desde tu frontend React
cors:
  allowedOrigins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

