INSERT INTO TCYCLE(NAME) VALUES ('CICLO 2025 - 2');
INSERT INTO TCYCLE(NAME) VALUES ('CICLO 2026 - 1');
INSERT INTO TCYCLE(NAME) VALUES ('CICLO 2026 - 2');

INSERT INTO TCOURSE(NAME, ABBREVIATION) VALUES ('Números y Operaciones','NYO');
INSERT INTO TCOURSE(NAME, ABBREVIATION) VALUES ('Geometría','GEO');
INSERT INTO TCOURSE(NAME, ABBREVIATION) VALUES ('Álgebra','X');
INSERT INTO TCOURSE(NAME, ABBREVIATION) VALUES ('Trigonometría','TRIG');
INSERT INTO TCOURSE(NAME, ABBREVIATION) VALUES ('Estadística','EST');

INSERT INTO TAREA(NAME, ABBREVIATION) VALUES ('Ciencias','CC');
INSERT INTO TAREA(NAME, ABBREVIATION) VALUES ('Letras','LL');
INSERT INTO TAREA(NAME, ABBREVIATION) VALUES ('Arquitectura','Q');
INSERT INTO TAREA(NAME, ABBREVIATION) VALUES ('Biomédica','B');
INSERT INTO TAREA(NAME, ABBREVIATION) VALUES ('Derecho','D');
INSERT INTO TAREA(NAME, ABBREVIATION) VALUES ('Artes','A');

INSERT INTO TROLE(NAME) VALUES ('ROLE_ADMIN');
INSERT INTO TROLE(NAME) VALUES ('ROLE_TUTOR');
INSERT INTO TROLE(NAME) VALUES ('ROLE_DIRECTOR');
